# Generated by Django 6.0 on 2025-12-08 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_empresa', models.BooleanField(default=False, verbose_name='¿Es Empresa?')),
                ('titular', models.CharField(max_length=200, verbose_name='Nombre Titular')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('documento_identidad', models.CharField(max_length=20, unique=True, verbose_name='DNI / CIF')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_compania_actual', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=10)),
                ('cuenta_bancaria', models.CharField(max_length=34, verbose_name='IBAN / Cuenta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AGENDADO', 'Agendado'), ('TRAMITADO', 'Tramitado'), ('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_cita', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('etiqueta', models.CharField(blank=True, help_text='Ej: Personal, Oficina', max_length=50)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='ventas.venta')),
            ],
        ),
    ]
